const truths = [
    "What's your biggest fear?",
    "What was your most embarrassing moment?",
    "If you could be invisible for a day, what would you do?",
    "Who was your first crush?",
    "What’s one thing you’ve never told anyone?",
    "Have you ever cheated on a test?",
    "What's the most trouble you've ever gotten into?",
    "What's your biggest regret?",
    "Have you ever lied to get out of plans?",
    "What's the weirdest thing you've ever eaten?",
    "Have you ever pretended to like a gift you hated?",
    "What's the most childish thing you still do?",
    "Have you ever had a secret nickname for someone?",
    "What's the biggest lie you've told your parents?",
    "Have you ever snooped through someone else's things?",
    "What's the most embarrassing thing in your search history?",
    "Have you ever cried during a movie? Which one?",
    "What's something you're secretly proud of?",
    "Have you ever kept a secret you shouldn't have?",
    "What's the worst date you've ever been on?",
    "Have you ever pretended to be sick to avoid something?",
    "What's the most ridiculous rumor you've heard about yourself?",
    "Have you ever broken something and blamed someone else?",
    "What's your guilty pleasure song?",
    "Have you ever had a crush on a friend's partner?",
    "What's the most impulsive thing you've ever done?",
    "Have you ever stolen anything?",
    "What's something you're embarrassed to admit you like?",
    "Have you ever ghosted someone? Why?",
    "What's your biggest insecurity?",
    "Have you ever lied about your age?",
    "What's the strangest dream you've ever had?",
    "Have you ever pretended to know someone you didn't?",
    "What's the most expensive thing you've broken?",
    "Have you ever re-gifted a present?",
    "What's something you'd never do in front of others?",
    "Have you ever had a paranormal experience?",
    "What's your most irrational fear?",
    "Have you ever faked being good at something?",
    "What's the most childish argument you've had?",
    "Have you ever kept a diary? Did anyone read it?",
    "What's your biggest pet peeve?",
    "Have you ever had a crush on a teacher/boss?",
    "What's the worst advice you've ever given?",
    "Kiss, marry, kill with three celebrities",
    "What's the strangest habit you have?",
    "Have you ever pretended to laugh at a joke you didn't get?",
    "What's something you're secretly competitive about?",
    "Have you ever walked in on someone accidentally?",
    "What's the most embarrassing text you've sent to the wrong person?"
];

async function truthCommand(sock, chatId) {
    const randomTruth = truths[Math.floor(Math.random() * truths.length)];
    await sock.sendMessage(chatId, { text: `🔮 Truth: ${randomTruth}` });
}

module.exports = { truthCommand };